--- #this script is for jenkins sample purpose
- hosts: server2.abc.com
  user: root
  become: yes
  gather_facts: yes
  tasks:
  - name: install httpd package
    yum: name=httpd state=installed
  - name: copy a file
    copy: src=index.html dest=/var/www/html/index.html
  - name: starting httpd service
    service: name=httpd state=restarted
